apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test
  name: test-ucpcluster-editor-role
rules:
- apiGroups:
  - ucp.ucpcluster.com
  resources:
  - ucpclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ucp.ucpcluster.com
  resources:
  - ucpclusters/status
  verbs:
  - get
