---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ucp-ucpcluster-com-v1alpha1-ucpcluster
  failurePolicy: Fail
  name: mucpcluster.kb.io
  rules:
  - apiGroups:
    - ucp.ucpcluster.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ucpclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ucp-ucpcluster-com-v1alpha1-ucpcluster
  failurePolicy: Fail
  name: mucpcluster.kb.io
  rules:
  - apiGroups:
    - ucp.ucpcluster.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ucpclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ucp-ucpcluster-com-v1alpha1-ucpcluster
  failurePolicy: Fail
  name: vucpcluster.kb.io
  rules:
  - apiGroups:
    - ucp.ucpcluster.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ucpclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ucp-ucpcluster-com-v1alpha1-ucpcluster
  failurePolicy: Fail
  name: vucpcluster.kb.io
  rules:
  - apiGroups:
    - ucp.ucpcluster.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ucpclusters
  sideEffects: None
