# permissions for end users to view ucpclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: ucpcluster-viewer-role
rules:
- apiGroups:
  - ucp.ucpcluster.com
  resources:
  - ucpclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ucp.ucpcluster.com
  resources:
  - ucpclusters/status
  verbs:
  - get
